articles/urls.py
from django.urls import path

from .views import (
    article_create_view,
    article_detail_view,
    article_search_view
)

app_name = 'articles'
urlpatterns = [
    path(r'', article_search_view, name='search'),
    path(r'create/', article_create_view, name='create'),
    path(r'<slug:slug>/', article_detail_view, name='detail'),

]

recipes/urls.py
from django.urls import path

from .views import (
    recipe_list_view,
    recipe_detail_view,
    recipe_create_view,
    recipe_update_view,
    recipe_detail_hx_view,
    recipe_ingredient_update_hx_view,
)

app_name = "recipes"
urlpatterns = [
    path("", recipe_list_view, name="list"),
    path("create/", recipe_create_view, name="create"),
    path(
        "hx/<int:parent_id>/ingredient/<int:id>/",
        recipe_ingredient_update_hx_view,
        name="hx-ingredient-detail",
    ),
    path(
        "hx/<int:parent_id>/ingredient/",
        recipe_ingredient_update_hx_view,
        name="hx-ingredient-create",
    ),
    path("hx/<int:id>/", recipe_detail_hx_view, name="hx-detail"),
    path("<int:id>/edit/", recipe_update_view, name="update"),
    path("<int:id>/", recipe_detail_view, name="detail"),
]

try_django/urls.py
from django.contrib import admin
from django.urls import path, include

from accounts.views import (
    login_view,
    logout_view,
    register_view
)
from articles.views import (
    article_create_view,
    article_detail_view,
    article_search_view
)
from .views import home_view

urlpatterns = [
    path('', home_view),
    path('pantry/recipes/', include('recipes.urls')),
    path('articles/', include("articles.urls")),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view)
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="https://unpkg.com/htmx.org@1.5.0"></script>
    <style>
        .htmx-indicator {
            display: none;
        }

        .htmx-request .htmx-indicator {
            display: inline;
        }

        .htmx-inverted-indicator {
            display: inline;
        }

        .htmx-request .htmx-inverted-indicator {
            display: none;
        }
    </style>
    <title>Try Django</title>
</head>
<body>
<h1>Hello World</h1>
<form action="/articles/">
    <label>
        <input type="text" name="q"/>
    </label>
    <input type="submit"/>
</form>
{% block content %}
{% endblock content %}

</body>
</html>

templates/home-view.html
{% extends "base.html" %}

{% block content %}
    <h1>{{ title }} (id:{{ id }})!</h1>
    <p>{{ content }}!</p>
    <a href='{% url "articles:create" %}'>Create article</a>
    <a href="{% url "articles:detail" slug="hello-world" %}">Hello world article</a>
    <ol>{% for x in object_list %}
        {% if x.title %}
            <li><a href="{{ x.get_absolute_url }}"> {{ x.title }} - {{ x.content }}</a></li>
        {% endif %}
    {% endfor %}
    </ol>
{% endblock content %}