recipes/urls.py
from django.urls import path

from .views import (
    recipe_list_view,
    recipe_detail_view,
    recipe_create_view,
    recipe_update_view,
    recipe_detail_hx_view,
    recipe_ingredient_update_hx_view,
)

app_name = "recipes"
urlpatterns = [
    path("", recipe_list_view, name="list"),
    path("create/", recipe_create_view, name="create"),
    path(
        "hx/<int:parent_id>/ingredient/<int:id>/",
        recipe_ingredient_update_hx_view,
        name="hx-ingredient-detail",
    ),
    path(
        "hx/<int:parent_id>/ingredient/",
        recipe_ingredient_update_hx_view,
        name="hx-ingredient-create",
    ),
    path("hx/<int:id>/", recipe_detail_hx_view, name="hx-detail"),
    path("<int:id>/edit/", recipe_update_view, name="update"),
    path("<int:id>/", recipe_detail_view, name="detail"),
]

try_django/urls.py
from django.contrib import admin
from django.urls import path, include

from accounts.views import (
    login_view,
    logout_view,
    register_view
)
from articles.views import (
    article_create_view,
    article_detail_view,
    article_search_view
)
from .views import home_view

urlpatterns = [
    path('', home_view),
    path('pantry/recipes/', include('recipes.urls')),
    path('articles/', include("articles.urls")),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view)
]

recipes/models.py
import pint
from django.conf import settings
from django.db import models
from django.urls import reverse

from .utils import number_str_to_float
from .validators import validate_unit_of_measure


# Create your models here.


class Recipe(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    directions = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    def get_absolute_url(self):
        return reverse("recipes:detail", kwargs={"id": self.id})

    def get_edit_url(self):
        return reverse("recipes:update", kwargs={"id": self.id})

    def get_hx_url(self):
        return reverse("recipes:hx-detail", kwargs={"id": self.id})

    def get_ingredients_children(self):
        return self.recipeingredient_set.all()


class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True, null=True)
    quantity = models.CharField(max_length=50)
    quantity_as_float = models.FloatField(blank=True, null=True)
    # pounds, lbs, oz, gram, etc
    unit = models.CharField(max_length=50, validators=[validate_unit_of_measure])
    directions = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # active = models.BooleanField(default=True)

    def get_absolute_url(self):
        return self.recipe.get_absolute_url()

    def get_hx_edit_url(self):
        kwargs = {
            "parent_id": self.recipe.id,
            "id": self.id
        }
        return reverse("recipes:hx-ingredient-detail", kwargs=kwargs)

    def convert_to_system(self, system="mks"):
        if self.quantity_as_float is None:
            return None
        ureg = pint.UnitRegistry(system=system)
        measurement = self.quantity_as_float * ureg[self.unit]
        return measurement

    def as_mks(self):
        # meter, kilogram, second
        measurement = self.convert_to_system(system='mks')
        return measurement.to_base_units()

    def as_imperial(self):
        measurement = self.convert_to_system(system="imperial")
        # print(measurement)
        return measurement.to_base_units()

    def save(self, *args, **kwargs):
        qty = self.quantity
        qty_as_float, qty_as_float_success = number_str_to_float(qty)
        if qty_as_float_success:
            self.quantity_as_float = qty_as_float
        else:
            self.quantity_as_float = None
        super().save(*args, **kwargs)

recipes/forms.py
from django import forms

from .models import Recipe, RecipeIngredient


class RecipeForm(forms.ModelForm):
    error_css_class = "error-field"
    required_css_class = "required-field"
    name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Recipe Name"}),
                           help_text="This is your help! <a href="">Contact us!</a>")

    # description = forms.CharField(widget=forms.Textarea(attrs={"rows": 3}))

    class Meta:
        model = Recipe
        fields = ['name', 'description', 'directions']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            new_data = {
                "placeholder": f'Recipe {str(field)}',
                "class": "form-control",
                # "hx-post": ".",
                # "hx-trigger": "keyup changed delay:500ms",
                # "hx-target": "#recipe-container",
                # "hx-swap": "outerHTML"
            }
            self.fields[str(field)].widget.attrs.update(new_data)
        # self.fields['name'].label = ''
        # self.fields['name'].widget.attrs.update({'class': 'form-control-2'})
        self.fields['description'].widget.attrs.update({'rows': '2'})
        self.fields['directions'].widget.attrs.update({'rows': '4'})


class RecipeIngredientForm(forms.ModelForm):
    class Meta:
        model = RecipeIngredient
        fields = ['name', 'quantity', 'unit']

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse

from .forms import RecipeForm, RecipeIngredientForm
from .models import Recipe, RecipeIngredient


# Create your views here.


@login_required
def recipe_list_view(request, id=None):
    qs = Recipe.objects.filter(user=request.user)
    context = {"object_list": qs}
    return render(request, "recipes/list.html", context)


@login_required
def recipe_detail_view(request, id=None):
    hx_url = reverse("recipes:hx-detail", kwargs={"id": id})
    context = {"hx_url": hx_url}
    return render(request, "recipes/detail.html", context)


@login_required
def recipe_detail_hx_view(request, id=None):
    if not request.htmx:
        raise Http404
    try:
        obj = Recipe.objects.get(id=id, user=request.user)
    except Recipe.DoesNotExist:
        obj = None
    if obj is None:
        return HttpResponse("Not Found")
    context = {"object": obj}
    return render(request, "recipes/partials/detail.html", context)


@login_required
def recipe_create_view(request):
    form = RecipeForm(request.POST or None)
    context = {"form": form}
    if form.is_valid():
        obj = form.save(commit=False)
        obj.user = request.user
        obj.save()
        if request.htmx:
            headers = {
                "HX-Redirect": obj.get_absolute_url()
            }
            return HttpResponse("created", headers=headers)
        return redirect(obj.get_absolute_url())
    return render(request, "recipes/create-update.html", context)


@login_required
def recipe_update_view(request, id=None):
    obj = get_object_or_404(Recipe, id=id, user=request.user)
    form = RecipeForm(request.POST or None, instance=obj)
    new_ingredient_url = reverse("recipes:hx-ingredient-create", kwargs={"parent_id": obj.id})

    context = {"form": form, "object": obj, "new_ingredient_url": new_ingredient_url}
    if form.is_valid():
        form.save()
        context["message"] = "Data Saved"
    if request.htmx:
        return render(request, "recipes/partials/forms.html", context)
    return render(request, "recipes/create-update.html", context)


@login_required
def recipe_ingredient_update_hx_view(request, parent_id=None, id=None):
    if not request.htmx:
        raise Http404
    try:
        parent_obj = Recipe.objects.get(id=parent_id, user=request.user)
    except Recipe.DoesNotExist:
        parent_obj = None
    if parent_obj is None:
        return HttpResponse("Not Found")
    instance = None
    if id is not None:
        try:
            instance = RecipeIngredient.objects.get(recipe=parent_obj, id=id)
        except RecipeIngredient.DoesNotExist:
            instance = None
    form = RecipeIngredientForm(request.POST or None, instance=instance)
    url = reverse("recipes:hx-ingredient-create", kwargs={"parent_id": parent_obj.id})
    if instance:
        url = instance.get_hx_edit_url()
    context = {"object": instance, "form": form, "url": url}
    if form.is_valid():
        new_obj = form.save(commit=False)
        if instance is None:
            new_obj.recipe = parent_obj
        new_obj.save()
        context['object'] = new_obj
        return render(request, "recipes/partials/ingredient-inline.html", context)
    return render(request, "recipes/partials/ingredient-form.html", context)

templates/recipes/create-update.html
{% extends "base.html" %}

{% block content %}
    <style>
        .ingredient-form {
            border-bottom: 1px solid black;
        }

        .hidden {
            display: none;
        }
    </style>

    <div style="margin-top:30px;">
        {% include 'recipes/partials/forms.html' %}

        <h3>Ingredients</h3>
        {% for ingredient in object.get_ingredients_children %}
            {% include 'recipes/partials/ingredient-inline.html' with object=ingredient %}
        {% endfor %}
        {% if new_ingredient_url %}
            <div id="ingredient-create">

            </div>
            <button hx-get="{{ new_ingredient_url }}" hx-trigger="click" hx-target="#ingredient-create"
                    hx-swap="beforeend">Add Ingredient
            </button>
        {% endif %}
    </div>

    <script>

        const addMoreBtn = document.getElementById("add-more")
        document.addEventListener('click', (event) => {
            if (event.target.id === 'add-more') {
                add_new_form(event)
            }
        })
        addMoreBtn.addEventListener('click', add_new_form)

        function add_new_form(event) {
            if (event) {
                event.preventDefault()
            }
            const totalNewForms = document.getElementById('id_form-TOTAL_FORMS')
            const currentIngredientForms = document.getElementsByClassName('ingredient-form')
            let currentFormCount = currentIngredientForms.length
            const formCopyTarget = document.getElementById("ingredient-form-list")
            const copyEmptyFormEl = document.getElementById("empty-form").cloneNode(true)

            copyEmptyFormEl.setAttribute('class', 'ingredient-form')
            copyEmptyFormEl.setAttribute('id', `form-${currentFormCount}`)
            formCopyTarget.append(copyEmptyFormEl)
            const regex = new RegExp('__prefix__', 'g')
            copyEmptyFormEl.innerHTML = copyEmptyFormEl.innerHTML.replace(regex, currentFormCount)
            totalNewForms.setAttribute('value', (currentFormCount + 1).toString())
            formCopyTarget.append(copyEmptyFormEl)

        }
    </script>

{% endblock content %}

templates/recipes/detail.html
{% extends 'base.html' %}

{% block content %}
    <div hx-get="{{ hx_url }}" hx-trigger="revealed">
        <div class="htmx-indicator">Loading...</div>
    </div>


{% endblock content %}

templates/recipes/list.html
{% extends 'base.html' %}

{% block content %}
    <h1>My Recipes</h1>
    <a href='{% url "recipes:create" %}'>Add recipe</a>

    <ol>
        {% for x in object_list %}
            <li><a href="{{ x.get_absolute_url }}"> {{ x.name }}</a></li>
        {% endfor %}
    </ol>



{% endblock content %}